---
title: "Maria Schweer-Collins' Comprehensive Exam Paper"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(here)
library(rio)
d2 <- import(here("data", "CAPSL.sav"))
```


# Page 1 {data-icons="fa-child"}

Column {data-width=650}
-----------------------------------------------------------------------

### RSA Trajectories by Child Age





```{r updated, fig.width=8, fig.height=6, echo = FALSE}
d2 %>% 
  filter(!is.na(RSA)) %>%
  mutate(Age = factor(W1TCAGEY, levels = c(3, 4, 5, 6, 7),
                           labels = c("Age 3", "Age 4", "Age 5", "Age 6", "Age 7"))) %>% 
  # make age variable as factor with according labels
  ggplot(aes(x = Time, y = RSA)) +
  geom_line(aes(group = id),
            color = "gray70") +
  geom_smooth(method = "lm",
              formula = y ~ x + I(x^2),
              size = 1.5,
              se = FALSE,
              color = "#20A387FF") +
  facet_wrap(~Age,nrow = 1) +
  theme_minimal(base_size = 10) +
  scale_x_continuous(name = "Condition",
                     labels = c("Resting", "WJ-AP", "WJ-PV", "Recovery")) +
  labs(x = "Condition") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.spacing = unit(1, "lines"), # increasing space between facets
        panel.grid.minor = element_blank(),
        plot.title = element_text(face = "bold")) # bold the title}

```




Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

